extends = "vendor/webware/webware-tools/mago.toml"
php-version = "8.4.1"

[linter]
baseline = "lint-baseline.toml"

[analyzer]
baseline = "analysis-baseline.toml"

[source]
paths = ["src", "test"]
includes = ["vendor"]
